### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by Joelius300** [Joelius300/werewolf-guide#4]
## Framework level

- [x] Switch to VitePress ~latest VuePress@v2 beta or see if VitePress is better suited now~
	- https://vitepress.dev/guide/data-loading#data-from-local-files
	- https://vitepress.dev/guide/routing#dynamic-routes
	- https://vitepress.dev/reference/default-theme-search#local-search
	- https://vitepress.dev/guide/sitemap-generation
	- https://github.com/vite-pwa/vitepress
	- https://vitepress.dev/guide/routing#generating-clean-url
	- https://vitepress.dev/guide/i18n
	- https://vitepress.dev/guide/extending-default-theme
	- Need to check for
		- Footnotes
		- Badges (or other way of showing team for a character)
- [x] Switch to new plausible sdk (https://github.com/Barbapapazes/plausible-tracker). deprecate your fork.
- [x] Change routes to be German too, put redirects into place to avoid breaking links (non-permanent ones, so you can translate everything later on and reuse the routes) 
	- DID NOT DO ANY REDIRECTS
- [ ] Github Action to publish to github pages
- [ ] swipe-in sidebar (https://github.com/vuejs/vitepress/issues/4330)
- [ ] update vitepress when https://github.com/vuejs/vitepress/issues/4331 is merged

## Content level

- [x] Rolle <-> Charakter, nur eines von beidem
- [ ] Gender everything (see #3)
- [ ] Add links to other roles for easier navigation

##  The glue between

- [ ] Automatically link to the teams with the badge
- [ ] List all roles of specific teams in the teams section?
